name: architecture_example
description: architecture_example for a vertical slice of an app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3+2
  rxdart: ^0.22.3
  animator: 1.0.0+5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
